// <auto-generated />
namespace Inventory.WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seeddata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seeddata));
        
        string IMigrationMetadata.Id
        {
            get { return "202102181549248_seed-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
